services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    volumes:
      - ./apps:/usr/src/app/apps
    ports:
      - '3000:3000'
  mongo:
    image: mongo
